# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: billing-billing-database
stringData:
  EGOLIA_BILLING_DATABASE_URL: ENC[AES256_GCM,data:C5zDHE3wxce+2+Obe42eFjWHTSq8Pdsv1p1ZW8tGwNUv8G6xfuyjtMQTTowNOusmUnsIOBctQHymYdW7Eg==,iv:8pali4SM7ehsOF26UK8iTVDAg8/JQ0aOr9vQeb2FE9k=,tag:eWMZxCakpAj87j6/yWn/Sw==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dytlcFVEUU1HUHR2L1pR
        TGhoMHBXWUg2QkRvNll1QUN1anUya1hZWFdFCnJ4UjJnVStFSTU0dDc1MW42elFS
        TURGN2xLTW5HZmk0c3Z4V3IySGFhRUUKLS0tIHZjUllSYTNXZyt4WU1LSGJvY3FP
        VDBoSnoxaEYwcUF3RWZQLzZtMno0YlEKbBj+gk72lWUmgVoxf1TgWxErsyvCzO/l
        3l8ob6KFW21LMbAmvWZD0rG0tCb6Nuxndg9n3pRicYkGATqTQTUTKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:13:28Z"
  mac: ENC[AES256_GCM,data:NEaz9o5uv4YAQopRv+r5nDF1MH/SKJ799HKQ3M2JEtAoWq90CrAs6xJt9D+MVYRfZ9ZnApuqOq6d8PmsZ/GyHCKG9Tf/Wm06O1RbfocErthW31iLnyAHVsQmgBDYAMdrzMa96U3Ex8cNVdWO+Ztv8xROjthIFjhYQ4FjDMTs/nQ=,iv:F65tPo6MHbrjDHaYcyZgOgQKtrUgn1EM3jIORoVNfnE=,tag:EvmY5ahDak00HBf6zb0LEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
