# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: billing-billing-database
stringData:
  EGOLIA_BILLING_DATABASE_URL: ENC[AES256_GCM,data:SSbHecvtKxNH80p49re+hQktrMsvje0nqZutDNw41k4CB6AUkHPAx+/er/VeXyBlFS76bvb/WgKhHJA=,iv:NAU5+aUVV+AKBg2ZAEbIh6RDS/z/POfy401l9rChRYE=,tag:viIrWNFXB4jaZWc47ICDaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDZpQmE5RENKN2xYYXBu
        NnNJSmtzOHZGTEVKOTZGUVloS0ZoZnZvR1F3ClZsUTRWQk5HcnlrbmUyLyt3eDl3
        Tkh4UWVQVFpNWUQ3NXFKRjBkeU1Da2sKLS0tIHp4RmhRWDVJZTZlNHJEY1NnVHha
        MGt6enlwUEM4SW95Y3JNWXVvM2FFN0UKnJ1MMd42tE3b5PKKp+Tf7WOvxmd8rFtc
        aLS6x4VTJaDgRcIsGZzi2JFbDlHE0J0Uvtj4NvcWRaANMz0R2UXtzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T17:37:35Z"
  mac: ENC[AES256_GCM,data:gVaTUKnUF3gScCf8gXtMvdoor1yMwPvlj7zM9elepW9F+ZgMI8XZB7oS8up4rsKMUKy6LVswe/B5axTF9nc3KVVIj1c2jsJ9mhAeduMu1X7lnrHdryvZv4D9lWGu52Yem+wTBQHUACS2Nfa80T1+tziZIY9y/mGuGvQrCLdmMK0=,iv:/OKIec/kRZvqYmVTMcsVK+vBBSkfR2rp4CaM+c+HzuQ=,tag:aGQNUZeuXH5mj4EgBHhWLA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
