# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: billing-billing-database-env
stringData:
  EGOLIA_BILLING_DATABASE_URL: ENC[AES256_GCM,data:JKGEZcnibnlpAN+Ujz1HNbF8w2qrVJrAzf5Fm57rNYPGeWKxH7VQAGjvJt9M09+2P/+VZ4X6c1BmHCo=,iv:skrynZopoio0nnFhQjtzujdi92jhKlf2SlWycbdGrPk=,tag:vdOjb3yF4NPW5B7dTafTOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d2g1SU1GRElnNkJkS0Zm
        SDdqb0FBMUdwOWwvdmZ5WFl6dTU2cnU0cGpFCkRiMmhJcjJzTW5LTUhQVGhHbElF
        MlJaRGd0NGVkeGpSVGtpemc5U1lQTzAKLS0tIDRjVVhrTTRyQk9uYlEvRVJyblQr
        QmgyZHZ1TDNTNkdnK1NYcDVzWHVBOVEKclyEfV5Z7prtvxy8abTReu3anzS1BJyR
        umndQj5e98cZeNmMF4+RqdMgkjgtqDpBjFkCF5zJvjUIlXmnN1M05A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T15:58:46Z"
  mac: ENC[AES256_GCM,data:+w9Lg2dOJWgwq9zEq+50tTvCoe8+YRXOcAJk0uhATRAuttcEvfw3I2nI4P4cF1Ku8O5tTmGNDJFVkt5Ldesp6ZhlaWVxjjLoSoXNT4aw7ZKqOmLfzb7NqM4QV5DXVihA4AyhnjHRYFB+99suoPBs0B4ObTfFxTy+cNBinVbcJDI=,iv:S22zYhdg8s3WpaR6fJ2QmaSXd0SQRVT/VfuD3qflgmE=,tag:Qw/BzovQdtbs01Xc/iLENw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
