# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: billing-billing-authentik
stringData:
  EGOLIA_BILLING_AUTHENTIK_HOST: ENC[AES256_GCM,data:wwhqeKXMa3Y9d6Wja7f1okOQJ7RhmfrUEFo=,iv:J/lkB+WlPOoR9vn7cqIGSydStGzzB6/LcYAsp5sjMuU=,tag:JI2TurllFPHnv4O9mQIImQ==,type:str]
  EGOLIA_BILLING_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:8IR6VDycckbZQH+zmIyAYFBKNCz0xN2Gm8QLq8QO2vybHgAlzD4aVr3ytOWQzlc5gDsELQ8Xk5BTrQAk,iv:BJ50L02LMTk3de/r0l8pMMM/x/CZrv/gpAnAHA839wE=,tag:OGKST6sTCMqKhtkeuY79dg==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd2ZIV1BrOEhVSnNreUEr
        NkhuTXlRNzhDNzFvUjdRNGh4UkZ4WmIzUjNBCjgreHAzVmo5aHZkeUlQUW1pTUZD
        ZHg4UkpqRTkxaElXRjkybEpvMmVVQjQKLS0tIERzMUZ4QWlsZHJEVEp4S1R0c09D
        ZnFoc3pkc01xbTNjT1o2bUlPWmZFTGsK4sh/rF0jxuBbCQ+njuIB3B+UVqil1RFk
        orob+jduDzFgBnV0DUjBz9O41WZN3PfR2W450LIC1qRbnNfNsbOqpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T16:44:33Z"
  mac: ENC[AES256_GCM,data:YZ8VxHExekZ0wKBXVypxs40SKrycICxn6tgG/xNLameNmH9NX4WZVzTMFaNhZC4b/lyo2RMsBjjMbKmRw1/gOe7cVHJrrLqErC/xv15mvHKdvnKY/Ec9rGvLhF+F4l4oQSdTf1oVoll/BZ33CvSVjoq2nmvpFC7B4BLcbUy7Dug=,iv:rcuGHjEs4uoZCfJCXn7CZocLRl/5y+bmNwP0LRPwULQ=,tag:F11XRHX7lRlkanN3th8VWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
