---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: billing-billing-authentik
stringData:
  EGOLIA_BILLING_AUTHENTIK_HOST: authentik-server.authentik
  EGOLIA_BILLING_AUTHENTIK_TOKEN:
