---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-billing
spec:
  template:
    spec:
      containers:
        - name: billing
          env:
            - name: EGOLIA_BILLING_SERVER_URL
              value: https://api.${PUBLIC_DOMAIN}

          envFrom:
            - configMapRef:
                name: billing-otel-env

  selector: {}
