---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: billing-billing
    includeSelectors: true
resources:
  - ../../../base/billing/billing/
  - ./grpcroute.yaml
  - ./httproute.yaml
  - ./otel.configmap.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./env.secret.patch.sops.yaml
  - path: ./service.patch.yaml
  - target:
      kind: Deployment
      name: billing-billing
    patch: |- # language: yaml
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: billing-otel-env
images:
  - name: ghcr.io/egolia-uit/billing
    newTag: dev-2605.23.1445
