# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: blog-blog-authentik
stringData:
  EGOLIA_BLOG_AUTHENTIK_HOST:
  EGOLIA_BLOG_AUTHENTIK_TOKEN:
