# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: blog-blog-database
stringData:
  EGOLIA_BLOG_DATABASE_URL: ENC[AES256_GCM,data:1happnozPJyiuSeklg8YkRq+RTW74USbguacTf3OtqbA0J6tPrdNMGLqmmqRFbH4zDrmSxGhTA==,iv:R98AExD9eHuB5RNZhf9YC8+z9a6pMwjqg4UL8OH88zk=,tag:wSGrurhd4kw2FjRPBnmDWg==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc1prZmZtM2dZcUl2c2ov
        UThNelVCQ25Ic2trN0E3SEV0R2ZwWk50ZGtJCnlwOUN5MDhPTkl1K1J0VWJ6TlI4
        MHVFQXA3c1gyQ3NJMVRpWm96SmtuNU0KLS0tIHBsSVEwMVhvNUJ6Y2hOR2lRZG8x
        TVpXMUV1dXpJeW5MaGFlQzRiUG9aVE0KlinL/lqkEOPOEbxtZsr/tF66OU1EE15F
        rAWJSx0c0pGE0b+gI221IAalKk1oRRnWWpg0zzWOb2aiVjd/Vuskow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:13:19Z"
  mac: ENC[AES256_GCM,data:bzdRqvRy2Ucff+WxlTsWAFocaEBNYrBPjAOJS9KekMI7uGLkc/AZ2ukZPZFoEMMPhJC49uZR33H1jbloK25Td0w6XTJUOn/wb/ywNixF+yA9AUebYPAMYMwYRbu9sYH7lrx/eRX8r+wnjL9bU3eOHAk59rppgiRZ3KVI+JV5Qts=,iv:VGmdz9prMz+41T9iTEyPCHwl7LKnboNltCK1JAhX1uo=,tag:n4rP45g5vSCWhGwhpc5QTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
