# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: blog-blog-database
stringData:
  EGOLIA_BLOG_DATABASE_URL: ENC[AES256_GCM,data:9GDR3wHUBmOluLG4oP1NCT+wGVweZNVUiFsZdXhVv0pHJ/IpNhAYAPaqH3LWk0wfEIo=,iv:ypeRJkUJsNZHCNHRX50q4TZU+Y0iUaAcNQPspaPXwhc=,tag:0dlcJMCH7LZMej01PSpcLQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cWMzUjBXb0d6bnVtcUNi
        MjYxTU94cUNHeUYwT1UveXIrM1lIeDZDVW1ZCkpoSXY5aTQ4emJzQ3Bhd0Y1Z0dr
        d0lyYzFtelh6WkdzMUVXVFpoYUx2MTAKLS0tIEtoZytUMlpXWk9uWmR5ZjBhNy9x
        SnE0VlJnMExrN3RYTnJJeWZhRG0rdkkKhELmU7L0kle0zw87+1GfRXzom7eU8u6Y
        9PJcqEvWGqHPzcjCCMzV4ORAuvxoRAn+4195yaYsrzMLjeMdE06hAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T17:38:02Z"
  mac: ENC[AES256_GCM,data:zoIxhBKJeFk6GBMo4+zhZo0WSf7OGxSfK+9DWQJcghml6++/nnsz0R7Oj9patGlmiRGFsr7n4cc/ZrMbapBqLc0ztqzjHfsuQp6/DBOOx3aXAtCQvblFZmDGIHOGEbhyS2euz6JAgp2JQjySYwj/wS2yH1KkPSCzbnanKM/LRAc=,iv:rw2BYXSZ3yoYxIF6vrUlzac0Awdp8usOpzaYndNSNh0=,tag:irdMNfDJLT6slsKJq6z12Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
