---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-web
spec:
  template:
    metadata:
      labels:
        istio.io/dataplane-mode: ambient
    spec:
      containers:
        - name: web
          env:
            - name: OTEL_TRACES_SAMPLER
              value: always_on
            - name: NEXT_OTEL_VERBOSE
              value: '1'

  selector: {}
