---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-otel-env
data:
  NEXT_OTEL_VERBOSE: '1'
  OTEL_SDK_DISABLED: 'false'
  OTEL_SERVICE_NAME: web
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy-alloy.monitoring:4318
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  OTEL_TRACES_SAMPLER: 'always_on'
