---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: course-course
    includeSelectors: true
resources:
  - ../../../base/course/course/
  - ./grpcroute.yaml
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./s3.secret.patch.sops.yaml
  - path: ./service.patch.yaml
images:
  - name: ghcr.io/egolia-uit/course
    newTag: dev-2604.25.1145
