# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: course-course-s3
stringData:
  EGOLIA_COURSE_S3_ENDPOINT: ENC[AES256_GCM,data:5sISwuApOH2/P/c18S5qKrG7ml3tfA==,iv:btkDshWy4eOHxdfqbLabxRLkbSZPQUHizqVriP8y9hE=,tag:r3aETYAmrEXjwRyWS7X52g==,type:str]
  EGOLIA_COURSE_S3_REGION_NAME: ENC[AES256_GCM,data:8+PHCVJj5q3r,iv:PaO5DeaXpBvJQ6I1p9f4Pd+a619VFdOVNuXgXom/Z2M=,tag:kQGdFxBfgw643PE8oP3oTA==,type:str]
  EGOLIA_COURSE_S3_BUCKET: ENC[AES256_GCM,data:etCpRsf8n93ooBFwQg==,iv:Q+l4+IadWETTgwHCcLr2WfkNZh3SEknqIFZ82+bAtFk=,tag:U6tcA9UF7YHRIuGJpCyf6w==,type:str]
  EGOLIA_COURSE_S3_ACCESS_KEY: ENC[AES256_GCM,data:O8B+k4KEOl077Ma+M+meuxLq444=,iv:SZHPuILrAJvsqOc+3oBtouOXkgynECeb9yQ70OdmFIA=,tag:kHwiCvo6OV15lKJJZDi65w==,type:str]
  EGOLIA_COURSE_S3_SECRET_KEY: ENC[AES256_GCM,data:1HyxiJCvkVmoSYXCFOOEwNLA3H77PFcHLK3kSI7GV6laUy8jQm1qHA==,iv:87IRauiWQumlHxSkDXG2l5CXcTe4fCEnDES+ycHjt7A=,tag:jp9WXt6uT8CyanWRePoSeA==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU1BIbW83R0dqSnBwUEda
        M0M3YnpKZnMxRWcrcUx3OXRJd2lIU05WSlhNCmFrVHR2THNEMUd2MWZ2OGtrQzRo
        RWlqYUt6WlhNNkQvV1NRbVB1WU41NGcKLS0tIGc5WmJzakJ5NHpKSzNNUFZ5UUcy
        Y1k1d0NIUkFzaVpmQVFtZ25kcmowZUEKFcK5LYjsQGH8SokgAxIN983x2eW1jFSY
        5LogX7jzSac8ccKNoUZnbqtu5umFKBTKVABK0Bho9ue+/UH6yaroRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T17:25:09Z"
  mac: ENC[AES256_GCM,data:J3eFb6spVrIF982s9VsEjKeh/v4HFYkxGYv12rjBl3R9pqtzHx0coAvXzxTCEJuSOvD1jupJGdTcz5Mlf7r5lHKy6yYLRXrD448ZXicgZVPJIbVBJEmwKUSfiVAWycKGukl88U6Ii5uhIv3bX1JGkeajX9Z3H1hta00PC6vdV+Y=,iv:xOsndDhjrN2GshJrrfjlNxoUsHUd2G0HD/+d7dSN3cg=,tag:S3HyRRWZXINxEwPEM3XeQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
