# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-course-auth
stringData:
  username: ENC[AES256_GCM,data:ShCDcvEKhQRL,iv:9VK0wzc64BZWrgZ0f/Sm05YbVNTchYTJSJYB89bhbdY=,tag:wEqOt4aJUP3dyZ3lakIdxQ==,type:str]
  password: ENC[AES256_GCM,data:yAsk7pmAJmt1,iv:YBNAXCytb1yaJhLOJ1/f5aksH4IZH8X1hJTG2/7vMVI=,tag:Hv7YDwFoqM6lx7XVJtYOEg==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4em5GNGlVVElvR0d3R1dZ
        Z09GWXh6RGpjSUlObG5yWUdqQkxldnJvelVNCjdQRldJbGRzSitzMWlJaE81cndl
        ODVaNDBrNnBRU1ZmWjYyd0FVWERVaGMKLS0tIHF0MVU5aWhhUlM0QkxPOE13WHFR
        bWhkTCt4eVgyZk9WUHMvTHhhWTk2SHMK/6bgZPDPRhvYedkU20a2HVIZ642PZ5yc
        8Ds3oPSPKfIa69c0iiK6hD0fGnqvELKcobbqYNuCV7bn329LoYHcUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:13:26Z"
  mac: ENC[AES256_GCM,data:EiHUrmzJLStlNvO7bL5yVaKTLZ9zdXqcyygC/awv5Y2Iyo7p14wI1SahCsShM+rniXD/nHUjoDbCcZ7YAlysd8RIQlyKEEZofDkrZP65GXI31IxQb1J5VWXsXL+mxzbtIntVmdqRsw8cP6L7/qJYin/MzWrRx5IUoxyBttdTKgs=,iv:AZzFYNCkHf3IEItmjQYJhpNqsGTNQ+ohGpJhS0Nf6fQ=,tag:3CpLrfQEz0ZoW+Z0wbqa5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
