# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-course-auth
stringData:
  username: ENC[AES256_GCM,data:zSY2B96T,iv:5Rup4WsGWCMfoHprK/KvuABdXjxX1xZOus10GRYsZuc=,tag:ElEZ/6HrIvXu7hpSltPJuQ==,type:str]
  password: ENC[AES256_GCM,data:ExFILS491uh9,iv:4V+t8VhmtjjGO4v1VmmfHCkFw3wJCpHIsxogAek7o/A=,tag:xyfoKz2nAz0YZnwbx+netA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaWNlOVJEeU5IcUNqOFhz
        bVNBVVFHUThOc09uY25YMUNOREVzYUhzc3lRClhXZEpiUXNaMitJM2YxVXludW8v
        ZTVucjJ6WmprUUZYTXQxRHVFNDRGOTAKLS0tIFpnN1RRUFUxbDQwZGMxaXZiQWQ5
        N3JITzA2SjJFL3ZsU2Y5em1qNXVmUjQKCmfoAE9Nwg8s6oFn3WrhjCa59YQQQs8H
        IHXlHMhlw4JBb/tDC8HY48SquUsRRaHWVhfcrujP2ViT9JETczQUVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T17:38:10Z"
  mac: ENC[AES256_GCM,data:swEPNb8N7jy5o1yVaG8+0OKl520On204EKVPB9jULOmTEqtQvl44UM3hPtn2dyynYYN+f4aijBVn+k7uSmhVV4r/gtmMD+wbJMzg6VZ4X9fqZ0rNkXSeB9qZVKzsLrWEhk9Q1BYuYCSknH3JCMTMuLLx8iEUTk5zaXWivWgS1YY=,iv:S0TMOmRLfK+M0IEWx1XxUBVAW8yYysmvId+GGjEIt7w=,tag:rz1tdI1t/9NXQgKwhJVxvQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
