---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: billing-cnpg
resources:
  - ../../../base/billing/cnpg/
  - ./allow-billing.authorizationpolicy.yaml
