---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/security.istio.io/authorizationpolicy_v1.json
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: egolia-ingress
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default
  action: ALLOW
  rules:
    - # Public
      to:
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            methods:
              - GET
            paths:
              - /course/courses-published
              - /course/courses/{*}/landing
              - /course/courses/{*}/reviews
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            paths:
              - /course/health/*

    - # Admin only
      from:
        - source:
            requestPrincipals:
              - '*'
      to:
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            methods:
              - POST
            paths:
              - /course/courses/{*}/approve
              - /course/courses/{*}/decline
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            paths:
              - /billing/admin/*
      when:
        - key: request.auth.claims[roles]
          values:
            - admin

    - # Instructor or Admin
      from:
        - source:
            requestPrincipals:
              - '*'
      to:
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            methods:
              - GET
            paths:
              - /course/my-courses
              - /course/courses-system
              - /course/courses/{*}/analytics
              - /course/courses/{*}/students
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            methods:
              - POST
            paths:
              - /course/courses
              - /course/courses/{*}/hide
              - /course/courses/{*}/upload-video-url
              - /course/courses/{*}/sections
              - /course/courses/{*}/sections/{*}/move
              - /course/courses/{*}/sections/{*}/lessons
              - /course/courses/{*}/sections/{*}/lessons/{*}/move
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            methods:
              - PUT
            paths:
              - /course/courses/{*}/basic-info
              - /course/courses/{*}/sections/{*}/lessons/{*}/test
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            methods:
              - PATCH
            paths:
              - /course/courses/{*}/sections/{*}
              - /course/courses/{*}/sections/{*}/lessons/{*}/video
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            methods:
              - DELETE
            paths:
              - /course/courses/{*}
              - /course/courses/{*}/hide
              - /course/courses/{*}/sections/{*}
              - /course/courses/{*}/sections/{*}/lessons/{*}
              - /course/lesson-comments/{*}
      when:
        - key: request.auth.claims[roles]
          values:
            - instructor
            - admin

    - # Authenticated
      from:
        - source:
            requestPrincipals:
              - '*'
      to:
        - operation:
            hosts:
              - egolia-api.${PUBLIC_DOMAIN}
            paths:
              - /course/*
              - /billing/*
              - /blog/post
              - /blog/post/*

    - # Dev gRPC Access
      from:
        - source:
            requestPrincipals: ['*']
      to:
        - operation:
            hosts:
              - egolia-grpc-api.${PUBLIC_HOST}
      when:
        - key: request.auth.claims[preferred_username]
          values:
            - kevinnitro
            - bighousevn

    - # Allow all other hosts
      to:
        - operation:
            hosts:
              - '*'
