---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/telemetry.istio.io/telemetry_v1.json
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: egolia-waypoint
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: egolia-waypoint
  accessLogging:
    - providers:
        - name: otel-log
  tracing:
    - providers:
        - name: otel-trace
      randomSamplingPercentage: 100
