# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: course-course-database
stringData:
  EGOLIA_COURSE_DATABASE_URL: ENC[AES256_GCM,data:qTmo7OxOyzjTiAKpQ3aS3lTxQHf6biAvOEYKf+QVCcVUdFrtUe7UxAzrof2/d4YlZZkbWpY3IzDehNTBIHiC+v6jpT+13kL8,iv:zHltSwKs7/HfRTCKzHinHx3KUtGv/8vFhN9fFY2ruz4=,tag:BTCKEiC0kKGz3LvkfMoxuQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna2ZYUjJ4STliTm5mb2E3
        dmlZU3YyN1d4ejEvN1diSkxxUE5ONEI1R1NvCjVRMlJ0dDA3OVZZOTVkclRSVGh2
        d2RtVmRZdm9xRkVPbDRHTWlEWExSWGcKLS0tIC9RQUY5clZ4Q25IcTZYenZ5TnJC
        bTY5QktXVVB1SlRYV09HU3YxUm5UcDAKH7rXuAO6qfD8ohnc5fr4J6WOww6vMkKp
        +xP341OTHioiwRohKGtBdcMaqZLBHqn+kMVuZ9r5rnSy7i1D4wz9+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T07:44:07Z"
  mac: ENC[AES256_GCM,data:/wi7dt5PgKySGR9zSmbE9VR/SERTRl6XfbALAo35RTyjsNIFTVT+i7lsbmV5wkWe6e3pjxDTmiwhPVhOwJp2DgY1vvHSKO/AB2f28ADwJVWLT71POBrr3zBX5K6Cm4biAHVeVe9HpCm0uRVPTLVsXtl2dGVDpO9gPQOJpzTCKBI=,iv:flByjekfOMfJTLgNfPECIQB/7VcDKTiuOM77P5O0clk=,tag:MByAswV5sKYISX0Twpotew==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
