# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: course-course-database
stringData:
  EGOLIA_COURSE_DATABASE_URL: ENC[AES256_GCM,data:Rd/IeHH2EAJw6Ed6jL84IUjRM33qsc2wI1wkY8czv65kGEjwkuvxoiU4as7nvGOcDFayMJiW9sOnmyg=,iv:tgW8RqW0VAeldPY/UfDsBtt59cThcYYrjjkOCIwyFjo=,tag:gOkfNjgkZabkDneezfp7kQ==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRCtMdk9lRzhwZ2lkWDM4
        bXpHRDNEZGJEcU5BbWtRUEZWVDMvNlg2eGxVCnNjN2grOHRqY1FIZXdxSEpuNXZB
        WUZuR1FmaGMyek9zYWwvWkhBNnhyL3MKLS0tIE4wSG9YVGNxZDlrRDNGdk5sNHBH
        bERVc3dFQklJWlFkVUJZaFI4eGp4c00K1alHPgpoV+4/w3dSNHb2Joi0pOuSZagS
        XRv8z2q36gGRsr6kmyoOslMChRHYufuTTmBkyl2/C8i+S2aBfRbi/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-04-25T17:13:25Z'
  mac: ENC[AES256_GCM,data:xQhBoCwlDQ9F56SZz4FQ9XPazI45pM+q37v1ycIyelmlTDte2L1kElsjWUL2wmIpMvkr7e171ngpxN+33+mN0Z4XNYgtHokcl5/Vd5TLHqZSchMZCHGbsxvp8/UT/eQt+6y1PqKSLYa+odf0PKmoFg02CrVATp9C9rMdDWOcNI8=,iv:gX3cuRJhJa8nqXg4y07Md4l+m19RH61kLGyFO1X0zFE=,tag:raI7duB+k8AFujceL4HWGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
