# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: course-course-database
stringData:
  EGOLIA_COURSE_DATABASE_URL: ENC[AES256_GCM,data:4DElT+wxyg8uQmwZJO7SfIa17QcVPdTaKQZmmHnreOGJAoh6rWdGuesDENXNoHTxYFxfnnV8c4M=,iv:wkYoS5uiQb0NfPmmv6g2mQAg5pNxCXa/+40hUvBb2pY=,tag:s13vdRcDG6MkwSQ3D9QDIg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNDVYWlFCQXYrZGRFZFdn
        Zk5VekdsZGNpTm5EdS85Z05EWjhkaUp5NFR3CnN2QTlZV2QwNzdoVDFvMGFjVHhI
        bjVSSDN0Q3A3enQ2NlFGZkdpazRhRzAKLS0tIGgzaHNkdGZKdHpiZjlrYkRPTjla
        S1FER2M3K2JqaXpVR1FvL1JRejd6VGMKrZNweEd+WJ0OnC0LAv4HpZx32H1j7AR6
        CjJekjpQtiS+Cp6O7ekMKQmsCj12LUQoeQw/6Fbhv7n7eEFJj5UaTQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T17:38:21Z"
  mac: ENC[AES256_GCM,data:x1ZkSGWR6PAS9LB9EPc+TFpBI5vcuL4O3cu1ksNCUkpJx3NXJ0ndgSmnqtoFAKHpzV3pBPGyudQFdIkSeSCMS4CHdrD8rojwjyaCyy2IEOWflEz3As3NrpsDbr32tvNArzbNewlLQqBi80d9W9UYLSfn2Ch/fp1g4nmKmpZvVoA=,iv:qdS19sKZHsTqzA76rxkI8ad3gdZ12E7FtoC+QS6SX5c=,tag:ufo/TKeZR6TIUH9GZbyykw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
