# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: course-course-env
stringData:
  EGOLIA_COURSE_DATABASE_URL: ENC[AES256_GCM,data:VM518/3ufCnoAwNnNRph+ydSfUETlKyI/f/lMsgDLd9mAA1V2zc26vmxeGau6NHZG/qPARFSGTQ=,iv:sHHsB//gfRUU37jTbDX6vLoEtMzvzwvWPG0+j8t/INY=,tag:hlaHYIx4tfBZ/36MwhTCFw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQzAxZ29tYnY5OU9aZ1R5
        bUxDVGRPcWNaaXBjNDA4M2YyV2RwQ0pVUG1RClMzVlZGNk5SZDNCNWJoTWR5UXg2
        aWIwelJndnB1Mjk3U3VVL3U5R0JsQ3MKLS0tIEtYcEYxZXQwTmNJU3VycG91cFVl
        TzhaM2o0Q2oreGp4c1hzazI1akNoakEKyyisSEyvQpkoNQMZFCNgtXr4yUuNp11/
        zaYgpgY8KnUqpMObg6t7jhODXxQKdjDzXKgEEDM8Vlj4cYQsE0LEaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T08:55:30Z"
  mac: ENC[AES256_GCM,data:G44CKjrwMeJPKzYhT0U3hOMHSnX432AJ6wkslLyVJhBIISfLDLtUt01kCdnMG5ftpeuAnmvQiwZOO8GIALs3YStQnqyEk1pil2XQZMOkoF97XRM3o/QhbxJL2Yoqhcq4hx4GBzpeiu/Rg6C4E8TBvF5u0r5Qab1S4yV5n/jH9nA=,iv:aGeuxhVWBYLDixlPjo0MNHaFahzfnuJ4LIL5GBvi3dI=,tag:EbXBtBVh3caMguu7oHm+RQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
