---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
kind: Kustomization
resources:
  - ./database.secret.sops.yaml
  - ./deployment.yaml
  - ./s3.secret.yaml
  - ./service.yaml
  - ./serviceaccount.yaml
