# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: course-course-s3
stringData:
  EGOLIA_COURSE_S3_ENDPOINT:
  EGOLIA_COURSE_S3_REGION_NAME:
  EGOLIA_COURSE_S3_BUCKET:
  EGOLIA_COURSE_S3_ACCESS_KEY:
  EGOLIA_COURSE_S3_SECRET_KEY:
