---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: blog-cnpg
resources:
  - ../../../base/blog/cnpg/
  # - ./allow-blog.authorizationpolicy.yaml
