---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: course-cnpg
resources:
  - ../../../base/course/cnpg/
  - ./allow-course.authorizationpolicy.yaml
