---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: egolia
  labels:
    istio.io/dataplane-mode: ambient

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: egolia-course
  labels:
    istio.io/dataplane-mode: ambient

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: egolia-billing
  labels:
    istio.io/dataplane-mode: ambient

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: egolia-blog
  labels:
    istio.io/dataplane-mode: ambient

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: egolia-web
  labels:
    istio.io/dataplane-mode: ambient
