# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: webhook
stringData:
  token: ENC[AES256_GCM,data:cFjt5AqXueuDs9dzeljc+1JivCkErG8ubZfkr2ha3b8nPW/U02g1kTD7AVk=,iv:Yk4ADUzb+p0pGWDCpWaY7QBbktaK0xg4/m+obvmNwM4=,tag:+XoY1+D+gXDbvadsZtj3sA==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OUx1dmJNOHgxN0hSdkpt
        Wk1BenZUZjlNQjNXNTJiQ3NadzdlK1cvSGowCjRmZk5xZEdRNFd2aFZtcmJVNXBU
        OXIwYzJJdjlnaFRoMjhRZFRpLzZ5Y00KLS0tIHhMTXFlRUJxT1RzOGt2ZExzdFBD
        Rnc3ZEs0bS9SRWYxald5T3lQeWRRZjgKxquZtJZ3+tedtI1yJPSqPGBZS/y4hGZJ
        YhRRMLQUujuMoUtvVUYq8LPcP4aaC8ZN84ZbetKdNQkVvLO9lD2LVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-04-25T18:36:39Z'
  mac: ENC[AES256_GCM,data:M4cRXU2YsTHF12Yl5ItoVsrUFL/GTD/krgCZDNwFF+fkF0qaCuUbWJmqC0rdXY1llZ+IK0da+eUEcTsDZHj2t7b/OuLYnqrd4YH+MYeWLxifiCRwbNlMxghx0/vbm7dzJYc5keURwawj5pi3z6+Zs6aH8p3gqQSWIbPJmymXxd4=,iv:+p697biKEnl65voIAZxEcA4LDx7Cf2mQuLioCdXDqz8=,tag:rrbEPJyXzBcQdN5mZes7ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
