# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-billing-auth
stringData:
  username: ENC[AES256_GCM,data:UA48SzXj+DmY,iv:ZMVH48PZT+XNegL9Owa/z1i4GIfgi4nHKgxtPPCJ1Tc=,tag:poySQwUSKSXkrQyX6QKBMQ==,type:str]
  password: ENC[AES256_GCM,data:fZp5hhPujwje,iv:2V4x8Vxu69JTrro7lJ078d8S4q3Bz53VJSLce/iF4ZE=,tag:Nnf21FCWGlw7rPJvM8u3aQ==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRzN6aFJNOWRrcDR4SlJ3
        eW9McFZHZmM0QWFzWWRidTd1YVorOUlIdWxNCnI4N3dsUzFieENjMDRaN29HWld4
        aW8wSGUxdTZmRnE5WlI1V0ZONGM4bkEKLS0tIFlJWTNKaU9EN01lNWNGQlg5eGtP
        VEpWaU9EaVpVV3BKZzBpYlhQQTJYSkkK9jWevpAAdYMlsU1NC1p1//l6suuhMT5k
        f+2izrkwqTAQB6Er1g1zYOJINbyEw01nd/QLB1kTtVKMXmySX0Q4cA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:12:58Z"
  mac: ENC[AES256_GCM,data:SUqLMir9faaLW64mDhnhh9FfOBxXjfaRaE7L5k0HY6hUXNpUuKkNZkTnyRdnIrnWmDS66tW5qUohBKAeNDm96aHPla5d0zgFTnnGnMK0wRoa8nJdpuCBdE7pDSDvnsrEjwkoggG0Qmk4DV1yOw8LZhpGsw4JqOhf3yiq07T/v2M=,iv:ngO+B1U7u1RXQhxq78hgL62wsHJ/bPZtSgNLpHLmy0Q=,tag:urW12CvwvlV7R3ACelPvwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
