# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-billing-auth
stringData:
  username: ENC[AES256_GCM,data:JGJQKuVsXA==,iv:xz3Z3y+ChnnaUACSdllW9kP7OuCBFjILNGqM7XsAJvM=,tag:ZAmzPe0uuAWyAKAqJNQaCw==,type:str]
  password: ENC[AES256_GCM,data:gpk6u9Laknqz,iv:NnPVVEpaZ16L2/7NrWzet1Im9AImufWvpl0rO+uKAQs=,tag:wTQ1voW9OfSzr2cmmvlZHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL05GSlV5ZThOSkdIeGsv
        eEhmaXdSUVI0anZ2WWpLZG9sYUFWZzZNSDNZCmIvSDJJb1hNOXpxTS9BMUVzODhy
        b0F2amIwOG43UTJ5dDluQmRnRUFuSlkKLS0tIGVjVHVzTTN1VWFHUTN3eWpOQTVR
        YTg4UlJONUM4ZGMwWjk1T2RBbERHOHcKa3CgDfptKeYv1wZHAfIjI2eTcvZQUmq4
        bvKgUgouQF+O/pz3jASvGArgYxunsXnJ2GyRVSB3u/1F7eKexL8Euw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T17:37:41Z"
  mac: ENC[AES256_GCM,data:o9dootvkAtJML97iSOosFtcKC50X6OnbGwPuwkHDvGxAHuvTmM7UzUKPO+s8GAG9v59AyQm9uii7OeI0ds7sYuU5UGI/TSQ1QGrWGqqnxBRulCBcWvG8DePZVvSolT/evm1i+S68H3io4dj7ZIkcDHOsGhqRk/a75FeU2sfC2rc=,iv:u2FnU2gEP5ciWWiLWm559Iwa33auVbezNzQhlt/51TY=,tag:mpZ98G82YmASJD1+xLIUiw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
