# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: blog-blog-authentik
stringData:
  EGOLIA_BLOG_AUTHENTIK_HOST: ENC[AES256_GCM,data:wCoxZVvGQXGJwmz+KZ/jn7NRd8fUMFZaTzU=,iv:vgdPoCTUbdqCZowl7FlRGr3A/4J86uOveIqFxgTEgaw=,tag:3wQjwAL0anSKbwbRT+CcCg==,type:str]
  EGOLIA_BLOG_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:rntsM640VpzldvLS+gANZIBk4TBNgweRb7ZLPvR+Qoi48ohcDVPdu4TzU2Vz8qGzSrUW2b0SPz4Sz1Za,iv:Hvnx6FOoT0f+uZvo4uo1Ybfs4NTXvjWbgLcKiBY8Amk=,tag:u8VO4rKvRZVNH4wDflnTcA==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNEF1N3h2Y2lUZTdCQ29n
        QXhtRjRkVjZVR0pLRjhoZUxjMFlwK0hrZlhvCjdiK1k4Vm9ZVXlURTNlU0Q0b25G
        U2FGc0NUemt1OXY4MTduNXlGemRHd2MKLS0tIE91Q1N3aVJPRCt4NDE3dUhsKzRk
        ZEFrQjl6MWJMQUltNHV2bDhDR0ROVG8KeGSIteeTYPrG6+1vvn+N7Xfo0L1iZPLG
        UaPB2dRnrKpJ6tISZCTtvnDYk+V0nAIpb7bf80LsXQl+gDIW8yiuHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T16:46:06Z"
  mac: ENC[AES256_GCM,data:uukt6dF6SMpkq5JzvX7910jaT1BgEcujSKiwdsoDy10mpIYbNubWinrecBvaVDnjAwjAx5Q3fLGPesKqm2SkwTi0kni00TY2p7/a0gyL5Q/Qk26QjvxUOkgY13kJ8RWAdkEQW1e8sC22kvzVp5trmNDpBsEeHpD9oK4HKe0KhIo=,iv:wIkw8/Nbn0xjAx76TUTVjoTEeZYfdVkDyfBhSVDfdsw=,tag:xZ4aPFiFdF7dnDU33oQfgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
