---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: blog-blog
    includeSelectors: true
resources:
  - ../../../base/blog/blog/
  - ./env.secret.sops.yaml
  - ./grpcroute.yaml
  - ./httproute.yaml
  - ./otel.configmap.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./service.patch.yaml
  - target:
      kind: Deployment
      name: blog-blog
    patch: |- # language: yaml
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: blog-blog-env
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: blog-otel-env
images:
  - name: ghcr.io/egolia-uit/blog
    newTag: dev-2605.09.1754
