---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service.json
apiVersion: v1
kind: Service
metadata:
  name: blog-blog
  labels:
    istio.io/use-waypoint: egolia-waypoint
    istio.io/use-waypoint-namespace: istio-system
