# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-blog-auth
stringData:
  username: ENC[AES256_GCM,data:ph7R7w5lts64,iv:Rlqx2kknqhr2K2skpnlvvhF+Ej1ASRfNg+78sWP/upM=,tag:8lroLRuG+uR4Pf8Cd2fAMg==,type:str]
  password: ENC[AES256_GCM,data:xjei3uIQd9Dl,iv:2KJJ6FLQDEolZ+lkV+NdCmE1H71NBbTRzE+fOKSpkj8=,tag:aUFGAk9y+3EgiGNgmgkwCg==,type:str]
sops:
  age:
    - recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RTJaQ2ZlUVN4dUo5a3Jl
        REYvUXVkWXQ2WDNKVDNPbk5YY2JjY0daYnpzCk9CTEVqTUYvYWVWR3p4bG02VDI3
        Nzk1eTNzMk53MzZsZTlhVGQxcnRJRjQKLS0tIDA2cW0wMHNGSWVCaUtvb1VMTEc0
        bzIwQnNzOUVOVVBmei83WjFGblNTTjAK36dS4H1MI09Jh5dYVr+67R3l/SxlIuan
        C+YObo4MCjmuxNL5yJbiDrEgaK1parXYM6eoNK45SD/7S+hSXSvxkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:13:23Z"
  mac: ENC[AES256_GCM,data:zU/WpgWBcUmI3WcLOjdg3JLjFU1RtDsMR2Zr+0n1BA8dWvtSBBdDRtN5ScKMGNiuoAA332fC1pvBC0oqRBlTaWEQNCSze3+DJarOesHIC9r/o6ZX7Bqfl/UmbH/SB3f4kAecCcA3fBB0fuIOU+5yHJfu1L5Bje2y0o2gjWvvsB8=,iv:gIkwDUEkqeU8Mbb7zafY9WqHibtlaTH+2EjOCB+nd18=,tag:dZQUZ2oqStH6FyJkkcvXOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
