---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-blog
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
  storage:
    size: 500Mi
  monitoring:
    enablePodMonitor: false
  postgresql:
    parameters:
      timezone: ${TIMEZONE}
      log_timezone: ${TIMEZONE}
  bootstrap:
    initdb:
      database: blog
      secret:
        name: cnpg-blog-auth
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
