# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-blog-auth
stringData:
  username: ENC[AES256_GCM,data:jANY9Q==,iv:YhF2K2Bm0f3wIezJhGVV0mX6zj82iLJ4nS4YnczjTAA=,tag:KKgsfTNcTThc4u9bZHVNog==,type:str]
  password: ENC[AES256_GCM,data:zTznQye5sVfk,iv:aZ+Pe3r/D6LfSI0/r2M/n/Efe+gCoR/OjejfATswrPc=,tag:BV1gn2WcqjSc2Zb7KLCtNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSDJWVllwMktVZ0V2THpX
        S0l2Y3R0ZjIyb0t5WFBQOU1kRCt3K3BZbFJjCnZBeDRpTzBDMHg5Q0lTbC9KT3Rv
        OEVNUEtrbEFVRjZDK0tNWEtqS2dBM28KLS0tIEtOQlBhUWFCbmVCcVl4QWU1aGFx
        QW40eWFjQzhrbW5BNWxqbGRvZGZXQ28KDvGvIY4n9JZ4MNR9TdK150v3K0Buj80x
        9BrU2eld8FhVXcd11wTMb1ln8u36foVd/jWLLmztDgyFY1cNT2BX9g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qnnhkehf4nwkdzs96eykvszef4s4500eagfymwpm5jsz4cjnze8s788029
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T17:37:52Z"
  mac: ENC[AES256_GCM,data:zBy8rw/oQpUbtNrv0eYvWE2++LdnXl0cNo7XdbTgjFt22S0FGPZoayRzQuSK6uyGNdtK7MRazEzjXFRndhM7KxNzYEWTUswharpwAKCrzofh+k9Mx1YDkw9+JRnxbIdCUK8T9eFZzem8f5rV8GHPQWbBpuwth26janEX+Zxc2/4=,iv:1eVLUE+hA9m3U47TlzOftOOG9OrhDxf+yXhdTG508QM=,tag:47+OafIvK/UbLQa7MlTojw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
